### ISSUE TITLE
Есть ли таймауты для клиента?

### ISSUE THREAD

**Issue by MatthewPattell** [lega911/ijson#2]
В README.md есть пример:
```
# 2. a client invokes the command
curl localhost:8001/test/command -d '{"id": 123, "params": "test data"}'
```

Как получить ошибку на клиенте если воркер падает с ошибками?
Как пример в логи inverted json падает:
```
400 no id for /rpc/result
```

Клиент так и остается ждать ответа, это повторяется бесконечно.

**Comment by lega911** [comment]
> Есть ли таймауты для клиента?

Это нужно устанавливать на клиенте, например для curl опция `--max-time`
https://unix.stackexchange.com/questions/94604/does-curl-have-a-timeout/94612#94612

> Как получить ошибку на клиенте если воркер падает с ошибками?

Для этого воркер должен подключится в keep-alive режиме (т.е. не должен отключатся после получения задачи), c заголовком type: get+ или worker
с curl так не получится, вот пример на python https://github.com/lega911/ijson/blob/master/example/python_worker2.py
