### ISSUE TITLE
0 security or am I missing something

### ISSUE THREAD

**Issue by JCKodel** [lega911/ijson#5]
If me, a customer, send a GET request with `type: get`, I can, basically, intercept any message sent to the server (because I'm registering myself as a worker).

Is that right?

There is absolutely no security at all to register a worker????

**Comment by lega911** [comment]
Hi, yes, any client can be a worker the same time, and vice versa.
It expects all parts of systems (microservices) work in trust environment with verified clients and workers.

if you want to expose some command (path) for unsafe clients you need to handle it by third-party service which will include not only ban to get tasks, but also auth, ddos-protection and other attacks.
